import { DM_Sans, Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Header from "./component/gobalcomponent/header";
import Footer from "./component/gobalcomponent/footer";


const outfit = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

const dmsans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"], 
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <body
        className={`${outfit.variable}  ${dmsans.variable} antialiased`}
      >
        <Header/>
        {children}
        
      </body>
      <Footer/>
    </html>
  );
}
